### ISSUE TITLE
Proxy is modifying the response headers

### ISSUE THREAD

**Issue by fjrial** [bulletmark/corsproxy#4]
My service is returning an image with a content-type : 'image/png' (tested by directly using my service with Postman)

But after passing my request through the proxy, the content-type is received as 'text/html; charset=UTF-8'

Can this response header be kept ??

**Comment by bulletmark** [comment]
This should be fixed by commit eb4259c366d4bd21286107767f4e3b30ff5ce514 on the latest master. Can you please confirm that works?

**Comment by fjrial** [comment]
Hi @bulletmark 
It works fine. Thank you!!
